/**
 * Recipe presets for sandbox terminals — parameterised bootstraps
 * that wire an agent CLI (Codex, Claude Code, Gemini) to point at
 * the user's local llama.cpp endpoint automatically, so a new
 * sandbox is useful the moment it boots.
 *
 * Each recipe resolves to a `CreateTerminalBody` via its `build(ctx)`
 * function — the caller supplies live context (backend URL, model
 * name, api key) at the moment of dispatch so we don't bake stale
 * values in.
 */

export interface RecipeContext {
	/** Base URL of the user's llama.cpp / OpenAI-compatible backend.
	 *  Includes scheme + host + port, no trailing slash. */
	backendBaseUrl: string;
	/** Current model name the user has selected (for agents that
	 *  need a default). Empty string is acceptable. */
	modelName: string;
	/** Optional API key for the backend. Empty string = no auth. */
	apiKey: string;
}

export interface RecipeBuild {
	bootstrap?: string;
	env?: Record<string, string>;
	files?: Array<{ path: string; content: string; mode?: number }>;
}

export interface Recipe {
	id: string;
	label: string;
	description: string;
	/** True if the recipe only makes sense when `RecipeContext.backendBaseUrl`
	 *  is set. The create form disables these recipes with a hint
	 *  when there's no backend to point at. */
	requiresBackend: boolean;
	build(ctx: RecipeContext): RecipeBuild;
}

function echoEndpoint(ctx: RecipeContext): string {
	const base = ctx.backendBaseUrl.replace(/\/+$/, '');
	return `echo "[ht-termd] Pointing agent at ${base}"`;
}

export const TERMINAL_RECIPES: Recipe[] = [
	{
		id: 'plain',
		label: 'Plain Ubuntu',
		description: 'Fresh root shell in the sandbox image. No bootstrap, no config.',
		requiresBackend: false,
		build: () => ({})
	},
	{
		id: 'codex-local',
		label: 'Codex → local model',
		description:
			"OpenAI Codex CLI pre-configured for the user's llama.cpp (OPENAI_BASE_URL + OPENAI_API_KEY + a ~/.codex/config.toml pointing at the selected model).",
		requiresBackend: true,
		build: (ctx) => {
			const baseUrl = ctx.backendBaseUrl.replace(/\/+$/, '') + '/v1';
			const apiKey = ctx.apiKey || 'local-no-auth';
			const model = ctx.modelName || 'local-default';
			const config = [
				'# Generated by ht-termd (Codex → local model recipe).',
				`model = "${model}"`,
				'',
				'[providers.local]',
				`base_url = "${baseUrl}"`,
				'env_key = "OPENAI_API_KEY"',
				'',
				'[[provider_config]]',
				'name = "local"',
				'approval_mode = "full-auto"',
				''
			].join('\n');
			return {
				env: {
					OPENAI_API_KEY: apiKey,
					OPENAI_BASE_URL: baseUrl,
					OPENAI_MODEL: model
				},
				files: [{ path: '/root/.codex/config.toml', content: config, mode: 0o600 }],
				bootstrap: `${echoEndpoint(ctx)}
mkdir -p /root/.codex
echo '[ht-termd] Codex config written to /root/.codex/config.toml'
echo '[ht-termd] Run: codex'`
			};
		}
	},
	{
		id: 'claude-local',
		label: 'Claude Code → local model',
		description:
			"Claude Code pointed at the user's llama.cpp via ANTHROPIC_BASE_URL. Works with any OpenAI-compatible-or-Anthropic-shim endpoint.",
		requiresBackend: true,
		build: (ctx) => {
			const base = ctx.backendBaseUrl.replace(/\/+$/, '');
			return {
				env: {
					ANTHROPIC_BASE_URL: base,
					ANTHROPIC_API_KEY: ctx.apiKey || 'local-no-auth'
				},
				bootstrap: `${echoEndpoint(ctx)}
echo '[ht-termd] ANTHROPIC_BASE_URL=${base}'
echo '[ht-termd] Run: claude'`
			};
		}
	},
	{
		id: 'gemini-local',
		label: 'Gemini CLI → local model',
		description:
			'Gemini CLI configured for a local endpoint. Useful when the backend exposes Gemini-shim paths.',
		requiresBackend: true,
		build: (ctx) => {
			const base = ctx.backendBaseUrl.replace(/\/+$/, '');
			return {
				env: {
					GEMINI_API_KEY: ctx.apiKey || 'local-no-auth',
					GOOGLE_API_KEY: ctx.apiKey || 'local-no-auth',
					GEMINI_API_BASE: base
				},
				bootstrap: `${echoEndpoint(ctx)}
echo '[ht-termd] Run: gemini'`
			};
		}
	}
];

export const DEFAULT_RECIPE_ID = 'plain';

export function resolveRecipe(id: string | null | undefined): Recipe {
	return (
		TERMINAL_RECIPES.find((r) => r.id === id) ??
		TERMINAL_RECIPES.find((r) => r.id === DEFAULT_RECIPE_ID) ??
		TERMINAL_RECIPES[0]
	);
}
